### ISSUE TITLE
topic-level configuration for kafka-monitor

### ISSUE THREAD

**Issue by Yiyun-Liang** [linkedin/kafka-monitor#101]
Hi! I am trying to set an override for the log retention time of the `kakfa-monitor` topic. I went through the code, and figured out that the way to do this may be as follows, which did not work. I was wondering if this is the right approach. Thank you very much.
In `kafka-monitor.properties`, I have:
```
"single-cluster-monitor": {
    "class.name": "com.linkedin.kmf.apps.SingleClusterMonitor",
    "topic": "kafka-monitor",
    "zookeeper.connect": "localhost:2181",
    "bootstrap.servers": "localhost:9092",
    "topic-management.topicCreationEnabled": true,
    ...
    "topic-management.topicFactory.props": {
    },
    "topic-management.topic.props": {
      "log.retention.ms": 3600000
    },
    ...
}
```

**Comment by lindong28** [comment]
@Yiyun-Liang Sorry for late reply. I was working on something when I saw your message two days ago but forgot to reply later.

I think your should probably use `retention.ms` instead of `log.retention.ms` in the `topic-management.topic.props`. I just pushed one commit to the master branch of kafka-monitor to provide this config in the example `kafka-monitor.properties`. Can you try it again?

**Comment by Yiyun-Liang** [comment]
Yes, I can definitely try that. Thank you very much.

**Comment by Yiyun-Liang** [comment]
Yes, `retention.ms` works. Thank you very much.
