### ISSUE TITLE
Page not found 404 error

### ISSUE THREAD

**Issue by shubham190892** [linkedin/kafka-monitor#116]
I am trying to run the monitor tool. But getting 404 on the browser by hitting the _localhost:8080/index.html_

**Comment by weizhenzhao** [comment]
I also met the 404 error
![image](https://user-images.githubusercontent.com/13706689/38918281-cfee270a-431f-11e8-8f1c-2ac3b75d2ba0.png)
![image](https://user-images.githubusercontent.com/13706689/38918324-e4abd25a-431f-11e8-84dc-12200f65b486.png)
Can some one help with me?

**Comment by lindong28** [comment]
@sbmc7 @weizhenzhao Sorry, the web GUI is only used for demo and we don't really use or support this in production at LinkedIn.

**Comment by lindong28** [comment]
Most likely the 404 error is related to local network setup, firewall setup etc.

**Comment by weizhenzhao** [comment]
@lindong28 
hi lindong
I just following the instructions in the readme

git clone https://github.com/linkedin/kafka-monitor.git
cd kafka-monitor 
./gradlew jar

and then change the kafka-monitor.properties to my own zookeeper and kafka endpoint
and run the following command:

./bin/kafka-monitor-start.sh config/kafka-monitor.properties

and in the http://localhost:8000/index.html
I still got the 404 error , I want to use the kafka-monitor because in this monday when my boss
showed our customers the kafka demo . the kafka servers shut down. So I want to install a kafka-monitor
to monitor the kafka running state.
Can you help me with the 404 error? 

So if the kafka-monitor doesn't support production visualization,
Don't you use the console to read the kafka monitor information?

**Comment by shubham190892** [comment]
@weizhenzhao @lindong28 
I tried with different port and it worked.
```
"jetty-service": {
    "class.name": "com.linkedin.kmf.services.JettyService",
    "jetty.port": 8001
  }
```
<img width="1269" alt="kafka" src="https://user-images.githubusercontent.com/6499319/39428018-8eaddadc-4ca3-11e8-8cf1-14ec5ef12fca.png">

**Comment by weizhenzhao** [comment]
@shubham190892 
sorry I still got 404 error
![default](https://user-images.githubusercontent.com/13706689/39502716-5930ce76-4df4-11e8-9ab5-ac4054509e0a.PNG)

**Comment by simplesteph** [comment]
For all those getting the 404 error, here's the fix: run the command from the `kafka-monitor` directory.

**Comment by lindong28** [comment]
Thanks for providing the solution @simplesteph!

I am closing this issue since we have a workaround solution and since the GUI in Kafka Monitor is not maintained actively by LinkedIn (as we don't use it) and used only for demo.

**Comment by jocelyndrean** [comment]
I used prometheus exporter and grafana, works like a charm :)

**Comment by elizagomes** [comment]
> I used prometheus exporter and grafana, works like a charm :)

@jocelyndrean I am trying to use prometheus exporter and grafana too, but I am not able to connect them. Could you show me how did you do that, please?
