### ISSUE TITLE
How to connect to kafka-monitor by jconsolejmx

### ISSUE THREAD

**Issue by CrazyCry** [linkedin/kafka-monitor#133]
On a monitor-kafka machine, I can directly select a local Process connection via jconsole, but now that I want a Remote connection, how should I fill in the Remote Process.
I tried to fill in with "service:jmx:rmi:///jndi/rmi://192.168.75.130:8778/jmxrmi",but conection failed.
![image](https://user-images.githubusercontent.com/15623287/44762904-52022700-ab7b-11e8-97ef-97d950e49a43.png)

**Comment by CrazyCry** [comment]
8778 should be the port of Jolokia.
Can I connect remotely via jconsole? If so, what is the port，thanks!

**Comment by lindong28** [comment]
@CrazyCry I think you can run prefix your command with `JMX_PORT=9105`, e.g. `JMX_PORT=9105 ./bin/kafka-monitor-start.sh config/kafka-monitor.properties`, so that Kafka Monitor JMX process will listen to JMX port. Then you can run jconsole and connect to e.g. remote_host_ip:9105, following instructions at https://docs.oracle.com/javase/7/docs/technotes/guides/management/jconsole.html.

**Comment by CrazyCry** [comment]
@lindong28 Thanks, I hava connect to kafka-monitor, I modify the kmf-run-class.sh file. add port manually.
