### ISSUE TITLE
Metrics description summary table

### ISSUE THREAD

**Issue by guilhemmarchand** [linkedin/kafka-monitor#138]
Hello !

Currently working in providing an open source application for Splunk and Kafka monitoring, I want to leverage the kafka-monitor as part of the end to end monitoring solution.

**Does it exist anywhere a table that references the metrics available with a brief description ?**

I do have access to all the metrics obviously and know what is available, what is less obvious is the very important KPIs to be monitored, eventually basis model for thresholds and differences between some of the metrics.

Thank you in advance for any kind recommendation you would have.

Regards,

Guilhem

**Comment by guilhemmarchand** [comment]
Hello,

I think I am ok now, but in my opinion it would great to have a just a brief summary table of the metrics.

For the records I came to the following dashboard:

![image](https://user-images.githubusercontent.com/7503059/47109920-7313f980-d247-11e8-8573-fe6e55a25342.png)

![image](https://user-images.githubusercontent.com/7503059/47109945-81621580-d247-11e8-8af7-1ce02fcae66f.png)

![image](https://user-images.githubusercontent.com/7503059/47109972-9474e580-d247-11e8-91e1-ce1b76182b38.png)

And the extractions of what looked to me like being the main KPIs:

![image](https://user-images.githubusercontent.com/7503059/47110035-b1a9b400-d247-11e8-8f27-44c7136d0bb8.png)

I am still very open to your suggestions ;-)

Kind regards,

Guilhem

**Comment by lindong28** [comment]
Thanks for opening this issue @guilhemmarchand. Sorry we have not been able to actively address kafka-monitor request from open source users in a faster manner. It will indeed be very useful and reasonable to have a table of metrics with explanation/importance in the wiki. I will try to provide a table later. We can keep this issue open before it is addressed.

**Comment by lindong28** [comment]
@guilhemmarchand Your list of metrics has covered all important metrics I can think of :)

BTW, instead of having a table of metrics in the github wiki, would it be reasonable to keep the update-to-date list of metrics in `config/kafka-monitor.properties` with comment explaining each metrics? The advantage of this solution is that 1) the important metrics can be used out-of-the-box when user runs `./bin/kafka-monitor-start.sh config/kafka-monitor.properties` as suggested in the wiki and 2) uses github repo (instead of github wiki) as only source-of-truth and less overhead for developer (currently mostly from LinkedIn) to maintain the wiki as we develop more metrics.

**Comment by guilhemmarchand** [comment]
Hi @lindong28 
No problem at all, and thank you very much for your reply.
Yes I think this would completely make sense, more than having the table in the readme file ;-)
