### ISSUE TITLE
Bug in creating additional partitions when the cluster grows

### ISSUE THREAD

**Issue by chrisbeard** [linkedin/kafka-monitor#228]
In upgrading to the latest version (v2.1.4) from v2.0.1, I've run into a regression in how additional topic partitions are added when a cluster grows in size.

The issue boils down to this [line](https://github.com/linkedin/kafka-monitor/blob/138fe46a06735f19e985dee8f27f4a8e82f572b3/src/main/java/com/linkedin/kmf/services/MultiClusterTopicManagementService.java#L310).
`replicaAssignment` will always be empty, which does not satisfy the requirements outlined by the docs for [increaseTo](https://kafka.apache.org/22/javadoc/org/apache/kafka/clients/admin/NewPartitions.html#increaseTo-int-java.util.List-). Thus, additional partitions will never be added and this malformed call will be reattempted each time the configured topic management interval triggers.

It looks like `replicaAssignment` was originally generated to support blacklisting brokers so they wouldn't be assigned additional partitions? I'm not really sure what the use-cases for this blacklist might be, but if it's no longer needed or isn't going to be supported anymore, it would be simpler to just let the controller perform the partition assignment here.

**Comment by andrewchoi5** [comment]
Hi @chrisbeard !

Great find. It's indeed the case that the length of the given newAssignments should equal totalCount - oldCount because the assignment of existing partitions are not changed.

```
>Increase the partition count for a topic to the given {@code totalCount}
     * assigning the new partitions according to the given {@code newAssignments}.
     * The length of the given {@code newAssignments} should equal {@code totalCount - oldCount}, since
     * the assignment of existing partitions are not changed.
     * Each inner list of {@code newAssignments} should have a length equal to
     * the topic's replication factor.
     * The first broker id in each inner list is the "preferred replica".</p>
```

At Linkedin we still do need `blacklistedBrokers` for our internal use case. I can review this class for needed changes. Or, would you want to open a PR for this issue? I or one of the reviewers would be happy to take a look and leave feedbacks. Thanks for reporting Chris!
