### ISSUE TITLE
Inaccurate consume latency metrics against older brokers

### ISSUE THREAD

**Issue by chrisbeard** [linkedin/kafka-monitor#233]
It appears that the consumer in `v2.4.0` of `kafka-clients` can lead to fetch requests being delayed (see [KAFKA-9724](https://issues.apache.org/jira/browse/KAFKA-9724)) against older brokers (i.e `2.2.0`), which affects consumer latency metrics.

In my case (tested with a `v2.2.0` cluster), I saw 99th percentile and max end-to-end latencies increase by and order of magnitude. For my own use, I've patched `kafka-clients` back to `2.3.1` against the `2.1.4` release of xinfra-monitor and latency measurements look normal again.

When the upstream issue gets fixed, upgrading to the latest `kafka-clients` release will be a big help!

**Comment by andrewchoi5** [comment]
Hello Chris!
Thanks for reporting this! I took a look at the JIRA ticket: https://issues.apache.org/jira/browse/KAFKA-9724, Consumer wrongly ignores fetched records since it no longer has valid position. 

It does seems like kafka-client version 2.4.0 with nodes @ version 2.2.0, consumers in a consumer group intermittently stop progressing on assigned partitions, even when there are messages to consume.


I will keep an eye out for this patch. Thanks again!
