### ISSUE TITLE
No access restrictor found, access to any MBean is allowed

### ISSUE THREAD

**Issue by NLP1r** [linkedin/kafka-monitor#27]
hi.
When I run the tools to monitor my own topic,Why always remind me "No access restrictor found, access to any MBean is allowed"？How can i solve it?

**Comment by lindong28** [comment]
@NLP1r I have never seen this message. Are you saying this message is printed repeatedly in the log? Can you copy&paste the log here?

**Comment by NLP1r** [comment]
@lindong28  No,when I delete end to end test in the config of kafka-monitor.properties.and run it .it's always remind me this message 
![image](https://cloud.githubusercontent.com/assets/21981099/19753300/11379a3a-9c36-11e6-86a0-cd96014c7732.png)

**Comment by lindong28** [comment]
@NLP1r Can you provide your entire kafka-monitor.properties? Have you started any ProduceService, ConsumeService or EndToEndTest?

**Comment by NLP1r** [comment]
It is my config files,I started endtoendtest,It just Test my Kafka,Produce message and consume,I want to monitor my own topic,How can I add to my Config files?Thank you.
![image](https://cloud.githubusercontent.com/assets/21981099/19768107/a27213c0-9c88-11e6-8247-902a18bd8931.png)

**Comment by lindong28** [comment]
OK. You started Kafka Monitor without any services that generates metrics.  This doesn't make sense for Kafka Monitor because the purpose of running Kafka Monitor is to monitor cluster and emit metrics via either log/JMX. DefaultMetricsReporterService reported that error message because it retries to read the metrics that doesn't exist. 

Kafka Monitor allows you to monitor your cluster using a topic that is not used by another other services. Kafka Monitor can not monitor a topic that is also produced/consumed by any other app.

You can monitor your cluster by running `./bin/kafka-monitor-start.sh config/kafka-monitor.properties` after providing the right value for `zookeeper.connect` and `bootstrap.servers` in `config/kafka-monitor.properties`. The `config/kafka-monitor.properties` in the repository provides a example with minimum configs needed to monitor a cluster.

**Comment by NLP1r** [comment]
@lindong28  .I am a newpie for kafka .Thanks for your patience response.

**Comment by lindong28** [comment]
@NLP1r Sure. You are welcome.
