### ISSUE TITLE
What's the difference between Kafka Monitor and Cruise Control?

### ISSUE THREAD

**Issue by idontknoooo** [linkedin/kafka-monitor#332]
I found Cruise Control also providing a way to monitoring Kafka cluster & partitions metrics. Thus, I am just wondering what's the major difference between the Cruise Control and Kafka Monitor?

Merry Christmas :)

**Comment by Lincong** [comment]
Hi @idontknoooo. Here is my understanding of these projects.

`Kafka Monitor`: it plays a role as a passive observer and reports what it observes (broker availability, produce/consume latency, etc) by emitting metrics. In other words, it pretends to be a Kafka user and keeps reporting metrics from the user's PoV.

`Kafka Cruise Control`: it monitors the Kafka cluster for a slightly different and broader range of things (broker availability, resource (CPU, disk, network I/O utilization) distribution, replica distribution,  etc). Cruise Control also detects and reports cluster anomalies (broker down, uneven resource/replica distribution) and `tries to move replicas around in the cluster to mitigate cluster anomalies and keep the cluster in a balanced state` (this process is called rebalance). This [talk](https://www.youtube.com/watch?v=ys05Zmo4Lwo) serves as a great introduction to Kafka Cruise Control.

Let me know if you have any questions and Merry Christmas!

**Comment by idontknoooo** [comment]
Hi @Lincong,

Thank you very much. I think you've answered my question. My team uses JMX exporter + Prom + Grafana for monitoring. I guess this is pretty much served the purpose just like Kafka Monitor? We are currently trying out CC to see how it can be used for partition rebalance with rack awareness. Thanks for the answer. You may close this issue.

**Comment by Lincong** [comment]
Hi @idontknoooo , I am not familiar with `Prom`. But I assume that your team basically loads Kafka metrics via JMX to some metrics graphics tools right? This approach of monitoring is different from what's provided by Kafka Monitor. Kafka Monitor is a standalone service itself and it does not use Kafka server metrics in any way. Instead it emits its own metrics based on what it has observed. Consider the following scenario.

Kafka cluster is healthy and no broker is down. That means all Kafka server metrics look good. If there is a network partition between the Kafka cluster and some Kafka users (including Kafka Monitor), Kafka server itself will not know. However, Kafka Monitor will detect this issue since it fails to produce to or consume from the Kafka cluster and it will emit metrics showing Kafka server unavailability. This is example showing why it is important to provide monitoring from the Kafka client/user's PoV.

Yes, Kafka Cruise Control can definitely help with `partition rebalance with rack awareness`. Feel free to checkout our [Cruise Control repo](https://github.com/linkedin/cruise-control).

**Comment by idontknoooo** [comment]
Ha you got my team right. I do see how Kafka Monitor plays its role now. Thank you soooo much!
