### ISSUE TITLE
no data on graph

### ISSUE THREAD

**Issue by tanuj83** [linkedin/kafka-monitor#84]
I don't see any data on graph at 
myserver:8000/index.html

I have no issue to run curl for port 8778 at server or my system

` curl localhost:8778/jolokia/read/kmf.services:type=produce-service,name=*/produce-availability-avg
{"request":{"mbean":"kmf.services:name=*,type=produce-service","attribute":"produce-availability-avg","type":"read"},"value":{"kmf.services:name=single-cluster-monitor,type=produce-service":{"produce-availability-avg":0.0}},"timestamp":1499340973,"status":200}`

All values are 0 for both the scripts and kafka-monitor.properties has correct Zk and bootstrap

executed first
` ./bin/kafka-monitor-start.sh config/kafka-monitor.properties`

The output as below

`[2017-07-06 11:53:28,744] INFO kmf:type=kafka-monitor:offline-runnable-count=0.0
kmf.services:name=single-cluster-monitor,type=produce-service:produce-availability-avg=0.0
kmf.services:name=single-cluster-monitor,type=consume-service:consume-availability-avg=0.0
kmf.services:name=single-cluster-monitor,type=produce-service:records-produced-total=0.0
kmf.services:name=single-cluster-monitor,type=consume-service:records-consumed-total=0.0
kmf.services:name=single-cluster-monitor,type=consume-service:records-lost-total=0.0
kmf.services:name=single-cluster-monitor,type=consume-service:records-duplicated-total=0.0
kmf.services:name=single-cluster-monitor,type=consume-service:records-delay-ms-avg=0.0
kmf.services:name=single-cluster-monitor,type=produce-service:records-produced-rate=0.0
kmf.services:name=single-cluster-monitor,type=produce-service:produce-error-rate=0.0
kmf.services:name=single-cluster-monitor,type=consume-service:consume-error-rate=0.0
 (com.linkedin.kmf.services.DefaultMetricsReporterService)`

and then 
`./bin/single-cluster-monitor.sh --topic test --broker-list myborker:9092 --zookeeper myZK:2181`

and see one exception 

`
Exception in thread "main" java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:433)
	at sun.nio.ch.Net.bind(Net.java:425)
[2017-07-06 12:14:49,816] DEBUG Reading reply sessionid:0x15cf2d02ad9649d, packet:: clientPath:null serverPath:null finished:false header:: 1,3  replyHeader:: 1,64424744367,0  request:: '/brokers/topics/kafka_monitor_1,F  response:: s{64424741794,64424741794,1499338106498,1499338106498,0,1,0,0,76,1,64424741797}  (org.apache.zookeeper.ClientCnxn)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at sun.net.httpserver.ServerImpl.<init>(ServerImpl.java:100)
	at sun.net.httpserver.HttpServerImpl.<init>(HttpServerImpl.java:50)
	at sun.net.httpserver.DefaultHttpServerProvider.createHttpServer(DefaultHttpServerProvider.java:35)
	at com.sun.net.httpserver.HttpServer.create(HttpServer.java:130)
	at org.jolokia.jvmagent.JolokiaServer.createHttpServer(JolokiaServer.java:243)
	at org.jolokia.jvmagent.JolokiaServer.init(JolokiaServer.java:171)
	at org.jolokia.jvmagent.JolokiaServer.<init>(JolokiaServer.java:81)
	at com.linkedin.kmf.services.JolokiaService.<init>(JolokiaService.java:32)
	at com.linkedin.kmf.apps.SingleClusterMonitor.main(SingleClusterMonitor.java:297)`

**Comment by sofoklisfountas** [comment]
I have the same issue. Running linkedin/kafka-monitor with wurstmeister/kafka-docker. No errors, I produce and consume messages successfully through wurstmeister but no changes in graphs and metrics both in web app and console.
I don't any errors with:
` ./bin/single-cluster-monitor.sh --topic test --broker-list kafka:9092 --zookeeper zookeeper:2181`

**Comment by lindong28** [comment]
Hey @sofoklisfountas, do you mean that the console output shows 0 messages are produced and consumed? If so, can you tell me how do you verify that messages are produced and consumed successfully?

**Comment by lindong28** [comment]
@tanuj83 Sorry for late reply. I missed this issue.

That exception you saw indicate that the port 8778 has already been used by another process. You can probably find the process by using `sudo ss -lptn 'sport = :8778'` (see https://unix.stackexchange.com/questions/106561/finding-the-pid-of-the-process-using-a-specific-port).

Regarding the problem that no messages are being produced and consumed by KafkaMonitor, can you first try using the open source script in Apache Kafka to produce and consume from your cluster and see if that works?

**Comment by sofoklisfountas** [comment]
@lindong28  Thanks for the quick response!

I am not experienced with kafka or docker so, I will post below with as much detail as I can, what I am doing exactly and what is the output I am getting from kafka-monitor (console).

I am using wurstmeister/kafka-docker.
I start wurstmeister/kafka-docker with `docker-compose up` on terminal window.

$ docker ps
![docker-ps](https://user-images.githubusercontent.com/26348780/33616853-692a109c-d9de-11e7-9baf-1190a1491e17.png)


- Then on seperate terminal windows: 
`$ docker exec -it kafkadocker_kafka_1 bash`
`kafka-console-producer.sh --broker-list kafka:9092 --topic test`

- and:
`$ docker exec -it kafkadocker_kafka_1 bash`
`kafka-console-consumer.sh --bootstrap-server kafka:9092 --topic test --from-beginning`

- I produce some messages: 
![producing](https://user-images.githubusercontent.com/26348780/33616661-cfcd662e-d9dd-11e7-8960-ffd09a1a075f.png)

- And I consume them:
![consuming](https://user-images.githubusercontent.com/26348780/33616758-22bf8402-d9de-11e7-8471-f757e5cf86b5.png)

- Output after consuming (On wurstmeister/kafka-docker  terminal window)
![output-after-consuming](https://user-images.githubusercontent.com/26348780/33616519-5da82868-d9dd-11e7-85b5-f2dc85055a97.png)

So far I am assuming that producing and consuming messages works fine.
Then I start kafka monitor since I build it:
`$ ./gradlew jar`
`$ ./bin/single-cluster-monitor.sh --topic test --broker-list kafka:9092 --zookeeper zoeeper:2181`

This is the output on console:
![output-on-start-kafka-monitor-1](https://user-images.githubusercontent.com/26348780/33617289-a29f6c9a-d9df-11e7-9013-802d4d183c3f.png)
![output-on-start-kafka-monitor-2](https://user-images.githubusercontent.com/26348780/33617526-3890f91c-d9e0-11e7-8c94-b4c4645b32d4.png)
![output-on-start-kafka-monitor-3](https://user-images.githubusercontent.com/26348780/33617597-68053e7e-d9e0-11e7-88cd-3f1ebe328883.png)

And the outuput on wurstmeister/kafka-docker console:
![output-when-start-kafka-monitor](https://user-images.githubusercontent.com/26348780/33619216-e1b03568-d9e4-11e7-9ccd-34900b238235.png)

- I leave the kafka-monitor running,
and when I produce and consume messages again (in the same way) the output in kafka-monitor is still like this:
![output-after-consuming-producing-kafka-monitor](https://user-images.githubusercontent.com/26348780/33620398-0ac7364c-d9e8-11e7-8105-85bbe9a12ee2.png)

The same results on the web app (everything at 0, nothing changes).

- My kafka-monitor.properties file is:
![kafka-monitor-properties](https://user-images.githubusercontent.com/26348780/33620561-7a7eb44c-d9e8-11e7-8b19-26fd517305ff.png)

What am I missing here? If you need any other information, please let me know.

**Comment by lindong28** [comment]
@sofoklisfountas The command `./bin/single-cluster-monitor.sh --topic test --broker-list kafka:9092 --zookeeper zoeeper:2181` you provided seems to use the wrong zookeeper url. Should it be zookeeper:2181?

Also, I am not very sure how kafka:9092 (and similarly zookeeper:2181) is resolved to the right ip:port. Can you try find out the actual ip of kafka (and zookeeper) and replace the url with ip:port?

**Comment by sofoklisfountas** [comment]
@lindong28 This was just a typo from copying and pasting the command from terminal (some kind of bug)
It was actually:` zookeeper:2181` 

Regarding, the kafka:9092. I think is how wurstmeister/kafka-docker is configured: because inside the kafkadocker_kafka_1 container in etc/hosts there is an entry 127.0.0.1 kafka. I don't know though what about zookeeper and if this answers you question. But as I showed you in the previous comment wurstmeister/kafka-docker with that configuration of localhost:port ( kafka:9092 and zookeeper:2181) I can produce and consume messages successfully as shown in the images above.
I have also tried to run wurstmeister/kafka-docker with the actual ip addresses but it didn't work for me.

As for your 2nd question, I run wurstmeister/kafka-docker with the working configuration (kafka:9092 and zookeeper:2181) and I changed in the kafka-monitor.properties file the hostnames with the actual ip addresses from docker containers, like:

`$ docker inspect kafkadocker_kafka_1`
![kafka-docker-container-inspect-ip](https://user-images.githubusercontent.com/26348780/33671826-fa251a68-daa8-11e7-99da-57a571436e4c.png)

`$ docker inspect kafkadocker_zookeeper_1 `
![kafka-zookeeper-container-inspect-ip](https://user-images.githubusercontent.com/26348780/33671832-fe07df8a-daa8-11e7-8984-4366edb6e2b9.png)

and kafka-monitor.properties:
![kafka-monitor-properties-ip](https://user-images.githubusercontent.com/26348780/33671976-55966212-daa9-11e7-9059-87e35ea7cfff.png)

and run:  `$ ./bin/single-cluster-monitor.sh --topic test --broker-list 172.18.0.3:9092 --zookeeper 172.18.0.2:2181`

and this is the output in kafka-monitor console:
![kafka-monitor-output-ip](https://user-images.githubusercontent.com/26348780/33672261-1b062dac-daaa-11e7-9553-b27f44c694f4.png)

It seems though, that this error is not relative to producing and consuming messages because after I do the output in kafka-monitor console is still the same to the above picture.

**Comment by lindong28** [comment]
@sofoklisfountas It looks like the producer in kafka monitor is not able to send any message to Kafka. Since kafka monitor directly instantiates the open source kafka producer with the same config which you have tested using kafka-console-producer, the only difference I can think of is in the code version.

Can you tell me the version (or githash) of the kafka-console-producer, kafka and kafka-monitor you used?

**Comment by sofoklisfountas** [comment]
I don't know how to find the versions but I suppose kafka-console-producer and kafka have the same version which is: kafka_2.12-1.0.0 and as for kafka-monitor I cloned the latest version (commit 6722470) from master branch.
If this not useful, could you be more specific and help me how to find the versions of each of these services?

**Comment by lindong28** [comment]
@sofoklisfountas Sorry, I have no idea why it does not work even though you can produce with kafka-console-producer... I tested kafka-monitor of git hash 6722470 with kafka 1.0.0 and it worked. I guess there is something in the docker setup that does not work with kafka-monitor. But I don't use docker myself and couldn't reproduce it.

**Comment by mfaraz-nisum-com** [comment]
Wondering if you were able to resolve this issue
