### ISSUE TITLE
Is there a metric exposed for latency/availability of individual broker/partition?

### ISSUE THREAD

**Issue by edvorkin** [linkedin/kafka-monitor#91]
I see there is latency for the whole cluster under monitoring, "The average latency of records from producer to consumer". (name=single-cluster-monitor,type=consume-service, records-delay-ms-avg".  Is there a way to see latency on individual hosts/broker to figure out if any broker is slow? Thanks

**Comment by lindong28** [comment]
Hey @edvorkin, we don't currently have this feature. I think this is because the original goal of kafka-monitor is to monitor the availability of Kafka service instead of the availability of individual brokers. I think it is a useful feature to extend the existing ProduceService to also report the availability per brokerId. I will ask and see if LinkedIn is going to implement this feature.

**Comment by AutoLui** [comment]
> Hey @edvorkin, we don't currently have this feature. I think this is because the original goal of kafka-monitor is to monitor the availability of Kafka service instead of the availability of individual brokers. I think it is a useful feature to extend the existing ProduceService to also report the availability per brokerId. I will ask and see if LinkedIn is going to implement this feature.

Hello @lindong28 , do you know if this feature has been implemented? I have been digging into the wiki, configs.properties and code but I cannot find  a way to expose per broker/partition metrics  so far.  Not sure if   ever since this question it was added as a feature, I might be lost if that's the case.

**Comment by lindong28** [comment]
@AutoLui This feature has not been implemented. This is a way to get the information with extra manual work. 

I guess what you need to figure out which broker causes the availability drop, right? If so, you can first check the latency/availability of the partition of the monitor topic by using the records-produced-rate-partition-{partitionId} and produce-error-rate-partition-{partitionId} defined [here](https://github.com/linkedin/kafka-monitor/blob/master/src/main/java/com/linkedin/xinfra/monitor/services/metrics/ProduceMetrics.java#L87). If partition's produced-rate is 0, or if its error rate is > 0, then the leader broker of this partition has problem.

**Comment by AutoLui** [comment]
Thanks @lindong28  ! I appreciate your answer, this will be pretty helpful in case we go extending this feature by ourselves.
